import './globals.css'
import {ClusterProvider} from '@/components/cluster/cluster-data-access'
import {BBAChainProvider} from '@/components/contexts/bbachain-provider'
import {UiLayout} from '@/components/ui/ui-layout'
import {ReactQueryProvider} from './react-query-provider'

export const metadata = {
  title: 'Scaffold',
  description: 'Generated by create-bbachain-dapp',
}

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
]

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <BBAChainProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </BBAChainProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
